---
title: 'Inflación y Gasto Público: ¿un dilema de política fiscal durante el COVID-19?'
subtitle: 'Países latinoamericanos miembros de la OCDE'
author: 
  - Ana Gabriela Ibarra
  - Ana Leticia Ibarra
  - Angelo Mazzoca
  - Reysbel Ramos
  - Sinai Suarez
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

<style>
body {
text-align: justify}
</style>

## Introducción

La inflación como fenómeno de estudio ha captado la atención de las investigaciones contemporáneas tomando en cuenta sus posibles orígenes. Particularmente, en épocas de inestabilidad económica, como la crisis financiera de 2008 y, más recientemente el COVID-19, se ha reafirmado la importancia del Gasto Público para hacer frente a los temas sociales, los cuales tienen un impacto en cuanto a gobernabilidad y estabilidad de los países.

En el presente informe, se busca realizar un análisis descriptivo respecto al impacto del gasto público en el comportamiento de la inflación, ello tomando en cuenta los países de América Latina que son miembros de la OCDE, y los estándares y compromisos inherentes a la condición de los mismos respecto a su participación en el organismo internacional.

Una cuestión preliminar es analizar la premisa propuesta por Lascano (s.f) el cual afirma que el nivel de gasto público no actúa como causa eficiente de la inflación, al menos desde un punto de partida. El autor destaca que las formas de financiamiento son relevantes en el análisis. Asimismo, sostiene que la política monetaria restrictiva no necesariamente es un vehículo para combatir la inflación en el largo plazo, por tanto, el análisis debe ser más profundo y las medidas más rigurosas de cara a su implementación.

Adicionalmente, es necesario tomar en cuenta las fechas de ingreso de cada país al organismo para una comprensión más rigurosa de los comportamientos que a continuación se evidenciarán: i) Chile, ingresa el 15 de diciembre de 2009; ii) Colombia, el 28 de abril de 2020; iii) Costa Rica, el 25 de mayo de 2021, consolidándose como el miembro más reciente de la región; iv) México, el 18 de mayo de 1994, siendo así el miembro más antiguo de América Latina. Como elemento adicional, debe señalarse que el ingreso de todos estos países contó con unanimidad y cumplimiento efectivo de los estándares exigidos por la organización.



## Tópico a abordar
El tópico de interés para el presente estudio es el análisis descriptivo de la inflación para los países miembros de la OCDE en América Latina, contemplando así posibles implicaciones en materia de política fiscal. Del tópico de interés se desprenden las siguientes interrogantes, a las que se busca dar respuesta:

- ¿Existe una correlación entre el gasto público y la inflación en los países?
- ¿En qué magnitud ha afectado el gasto público a la inflación?
- ¿En qué medida el COVID-19 impactó el nivel de gasto per cápita entre países? 
- ¿Hubo heterogeneidad en la estructura del gasto público entre los países?



## Descripción de los datos

En esta ocasión se empleará la [base de datos obtenida del Fondo Monetario Internacional](https://www.imf.org/en/Publications/WEO/weo-database/2022/April/weo-report?c=228,233,238,273,&s=PPPEX,PCPI,LP,GGX,&sy=1990&ey=2021&ssm=0&scsm=1&scc=0&ssd=1&ssc=0&sic=0&sort=country&ds=.&br=1).

Estaremos analizando las siguientes variables de los países Colombia, Chile, Costa Rica y México para el período comprendido entre los años 1990 y 2021:

- Población.
- Gasto público expresados en miles de millones en moneda local.
- Indice de inflación.
- Tasa implícita del PPA.


## Metodología

Previo al análisis de los datos, se debe realizar una transformación de los mismos. La misma consistirá en la limpieza y recopilación de los datos en una tabla unificada, así como cálculos adicionales de indicadores que permitirán realizar un análisis preciso. Asimismo, el proceso de limpieza de datos permitirá transformar los valores a ser evaluados, omitiendo aquellas observaciones que no sean de utilidad para las variables definidas.. Uno de los cálculos más importantes que realizaremos dentro de la transformación de los datos es el del  gasto público por país en dólares americanos, con el fin de estandarizar los valores entre países. De igual manera, se realizará el cálculo del gasto público per cápita por cada país, para así poder determinar la proporción del gasto destinado a cada habitante. 

Para dar respuesta a las incógnitas de investigación, se hará uso del análisis descriptivo de los indicadores previamente mencionados, un análisis de correlación entre variables, así como un análisis de regresión lineal en el que se explique la inflación en función del gasto público. Tanto para cada país de la muestra seleccionada, como a nivel agregado de la misma, se estimarán la siguientes regresiones de Mínimos Cuadrados Ordinarios: 



$$IPC_{ij} =  \beta_{0} + \beta_{1}Gasto_{ij} + \epsilon_{ij}$$



$$IPC_{ij} =  \beta_{0} + \beta_{1}Gastopc_{ij} + \epsilon_{ij}$$



Donde IPC es la inflación, Gasto es el gasto público del país medido en dólares americanos, Gastopc es el gasto público per cápita del país medido en dólares americanos. Así como i hace referencia a cada uno de los países de la muestra y j hace referencia a cada uno de los años en el rango de 1990 a 2021. Cabe destacar que los datos a analizar son datos de panel, es decir, las observaciones de cada país cambian a través del tiempo. 

Adicionalmente, se emplearán herramientas de visualización de datos, entre las que destacan gráficos para presentar las relaciones a estudiar, histogramas para el análisis de la distribución, además de ilustraciones comparativas que complementen el análisis que se pretende llevar a cabo. Lo anterior se realiza con el fin de analizar la información obtenida y aproximar así el comportamiento que evidencia el fenómeno planteado. 


## Enlaces de interés

- [Repositorio Github del Proyecto](https://github.com/analetty/dsci-proyecto-final)
- [Acerca de la OCDE](https://www.oecd.org/acerca/)